name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
            - name: Use Node.js v16
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Run ESLint
              run: yarn lint

    Build:
        name: Build Source Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
            - name: Use Node.js v16
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Build
              run: yarn build

    Testing:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
            - name: Use Node.js v16
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Test
              run: yarn test:coverage
            - name: Store code coverage report
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
              with:
                  name: coverage
                  path: coverage/

    Upload_Coverage_Report:
        name: Upload coverage report to codecov
        needs: [Testing]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
              with:
                  fetch-depth: 2
            - name: Download Coverage report
              uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2
              with:
                  name: coverage
                  path: coverage/
            - name: Codecov Upload
              uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # renovate: tag=v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: coverage/
                  fail_ci_if_error: true
